/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.moravian.solver;

import Boggle.Board;
import Boggle.Lexicon;
import Boggle.Searcher;
import WordSearch.WordSearchBoard;
import WordSearch.WordSearcher;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lewis
 */
public class Solver extends javax.swing.JFrame {

    /**
     * Creates new form Solver
     */
    public Solver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Games = new javax.swing.JComboBox();
        Pane = new javax.swing.JLayeredPane();
        BoggleBoard = new javax.swing.JPanel();
        Char00 = new javax.swing.JTextField();
        Char01 = new javax.swing.JTextField();
        Char02 = new javax.swing.JTextField();
        Char03 = new javax.swing.JTextField();
        Char10 = new javax.swing.JTextField();
        Char11 = new javax.swing.JTextField();
        Char12 = new javax.swing.JTextField();
        Char13 = new javax.swing.JTextField();
        Char20 = new javax.swing.JTextField();
        Char21 = new javax.swing.JTextField();
        Char22 = new javax.swing.JTextField();
        Char23 = new javax.swing.JTextField();
        Char30 = new javax.swing.JTextField();
        Char31 = new javax.swing.JTextField();
        Char32 = new javax.swing.JTextField();
        Char33 = new javax.swing.JTextField();
        WordSearchBoard = new javax.swing.JPanel();
        Let00 = new javax.swing.JTextField();
        Let01 = new javax.swing.JTextField();
        Let02 = new javax.swing.JTextField();
        Let03 = new javax.swing.JTextField();
        Let04 = new javax.swing.JTextField();
        Let05 = new javax.swing.JTextField();
        Let15 = new javax.swing.JTextField();
        Let14 = new javax.swing.JTextField();
        Let13 = new javax.swing.JTextField();
        Let12 = new javax.swing.JTextField();
        Let11 = new javax.swing.JTextField();
        Let10 = new javax.swing.JTextField();
        Let20 = new javax.swing.JTextField();
        Let21 = new javax.swing.JTextField();
        Let22 = new javax.swing.JTextField();
        Let23 = new javax.swing.JTextField();
        Let24 = new javax.swing.JTextField();
        Let25 = new javax.swing.JTextField();
        Let30 = new javax.swing.JTextField();
        Let31 = new javax.swing.JTextField();
        Let32 = new javax.swing.JTextField();
        Let33 = new javax.swing.JTextField();
        Let34 = new javax.swing.JTextField();
        Let35 = new javax.swing.JTextField();
        Let40 = new javax.swing.JTextField();
        Let41 = new javax.swing.JTextField();
        Let42 = new javax.swing.JTextField();
        Let43 = new javax.swing.JTextField();
        Let44 = new javax.swing.JTextField();
        Let45 = new javax.swing.JTextField();
        Let50 = new javax.swing.JTextField();
        Let51 = new javax.swing.JTextField();
        Let52 = new javax.swing.JTextField();
        Let53 = new javax.swing.JTextField();
        Let54 = new javax.swing.JTextField();
        Let55 = new javax.swing.JTextField();
        Solve = new javax.swing.JButton();
        Word = new javax.swing.JScrollPane();
        Words = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Games.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boggle", "Word Search" }));
        Games.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GamesActionPerformed(evt);
            }
        });

        Pane.setBackground(new java.awt.Color(0, 0, 0));
        Pane.setOpaque(true);

        BoggleBoard.setBackground(new java.awt.Color(0, 0, 0));

        Char00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Char00ActionPerformed(evt);
            }
        });

        Char01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Char01ActionPerformed(evt);
            }
        });

        Char02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Char02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BoggleBoardLayout = new javax.swing.GroupLayout(BoggleBoard);
        BoggleBoard.setLayout(BoggleBoardLayout);
        BoggleBoardLayout.setHorizontalGroup(
            BoggleBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoggleBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoggleBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Char30, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(Char10)
                    .addComponent(Char20)
                    .addComponent(Char00, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BoggleBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BoggleBoardLayout.createSequentialGroup()
                        .addGroup(BoggleBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Char01, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(Char11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BoggleBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BoggleBoardLayout.createSequentialGroup()
                                .addComponent(Char12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Char13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BoggleBoardLayout.createSequentialGroup()
                                .addComponent(Char02, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Char03, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(BoggleBoardLayout.createSequentialGroup()
                        .addGroup(BoggleBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Char21, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(Char31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BoggleBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Char22, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(Char32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BoggleBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Char23, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Char33, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        BoggleBoardLayout.setVerticalGroup(
            BoggleBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoggleBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BoggleBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Char00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Char01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Char02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Char03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BoggleBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Char10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Char11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Char12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Char13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BoggleBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Char21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Char20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Char22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Char23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BoggleBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Char30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Char31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Char32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Char33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        BoggleBoard.setBounds(0, 0, 310, 240);
        Pane.add(BoggleBoard, javax.swing.JLayeredPane.DEFAULT_LAYER);

        WordSearchBoard.setBackground(new java.awt.Color(0, 0, 0));

        Let00.setText("x");

        Let01.setText("x");

        Let02.setText("x");

        Let03.setText("x");

        Let04.setText("x");
        Let04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Let04ActionPerformed(evt);
            }
        });

        Let05.setText("x");

        Let15.setText("x");

        Let14.setText("x");

        Let13.setText("x");

        Let12.setText("x");

        Let11.setText("x");

        Let10.setText("x");

        Let20.setText("x");

        Let21.setText("x");

        Let22.setText("x");

        Let23.setText("x");

        Let24.setText("x");

        Let25.setText("x");

        Let30.setText("x");

        Let31.setText("x");

        Let32.setText("x");

        Let33.setText("x");

        Let34.setText("x");

        Let35.setText("x");

        Let40.setText("x");

        Let41.setText("x");

        Let42.setText("x");

        Let43.setText("x");

        Let44.setText("x");

        Let45.setText("x");

        Let50.setText("x");

        Let51.setText("h");

        Let52.setText("e");

        Let53.setText("l");

        Let54.setText("l");

        Let55.setText("o");

        javax.swing.GroupLayout WordSearchBoardLayout = new javax.swing.GroupLayout(WordSearchBoard);
        WordSearchBoard.setLayout(WordSearchBoardLayout);
        WordSearchBoardLayout.setHorizontalGroup(
            WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WordSearchBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WordSearchBoardLayout.createSequentialGroup()
                        .addComponent(Let20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WordSearchBoardLayout.createSequentialGroup()
                        .addComponent(Let30, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let34, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WordSearchBoardLayout.createSequentialGroup()
                        .addComponent(Let00, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let01, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let02, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let03, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let04, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let05, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WordSearchBoardLayout.createSequentialGroup()
                        .addComponent(Let10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Let15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WordSearchBoardLayout.createSequentialGroup()
                        .addGroup(WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Let50, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Let40, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Let41, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(Let51))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Let42, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(Let52))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Let43, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(Let53))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Let44, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(Let54))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Let45, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(Let55))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        WordSearchBoardLayout.setVerticalGroup(
            WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WordSearchBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Let00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Let10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Let11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Let12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Let13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Let14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Let15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Let20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Let30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Let40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WordSearchBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Let50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Let55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        WordSearchBoard.setBounds(0, 0, 290, 260);
        Pane.add(WordSearchBoard, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Solve.setText("Solve");
        Solve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolveActionPerformed(evt);
            }
        });

        Words.setColumns(20);
        Words.setRows(5);
        Word.setViewportView(Words);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Solve)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Games, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Word, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(Pane))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(Games, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Pane, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Word, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Solve)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Char00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Char00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Char00ActionPerformed

    private void Char01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Char01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Char01ActionPerformed

    private void Char02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Char02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Char02ActionPerformed

    private void Let04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Let04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Let04ActionPerformed

    private void GamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GamesActionPerformed
        
        String game = (String) Games.getSelectedItem();
        
        if ("Boggle".equals(game)) {
            Pane.setLayer(BoggleBoard, 0, 0);
        }
        else if ("Word Search".equals(game)) {
            Pane.setLayer(WordSearchBoard, 0, 0);
        }
        
    }//GEN-LAST:event_GamesActionPerformed

    private void SolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolveActionPerformed
        
        String game = (String) Games.getSelectedItem();
        
        if ("Boggle".equals(game)) {
            char[][] letters = new char[4][4];
        letters[0][0] = Char00.getText().charAt(0);
        letters[0][1] = Char01.getText().charAt(0);
        letters[0][2] = Char02.getText().charAt(0);
        letters[0][3] = Char03.getText().charAt(0);
        letters[1][0] = Char10.getText().charAt(0);
        letters[1][1] = Char11.getText().charAt(0);
        letters[1][2] = Char12.getText().charAt(0);
        letters[1][3] = Char13.getText().charAt(0);
        letters[2][0] = Char20.getText().charAt(0);
        letters[2][1] = Char21.getText().charAt(0);
        letters[2][2] = Char22.getText().charAt(0); 
        letters[2][3] = Char23.getText().charAt(0);
        letters[3][0] = Char30.getText().charAt(0);
        letters[3][1] = Char31.getText().charAt(0);
        letters[3][2] = Char32.getText().charAt(0); 
        letters[3][3] = Char33.getText().charAt(0);
                
        Lexicon lex = null;
        try {
            lex = new Lexicon("words.txt");
        } 
        catch (FileNotFoundException ex) {
            Logger.getLogger(Boggle.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (IOException ex) {
            Logger.getLogger(Boggle.class.getName()).log(Level.SEVERE, null, ex);
        }    
        
        Board board = new Board(letters);
        Searcher s = new Searcher(board, lex);
        s.search();
        
        Words.setText("Number of words = " + s.getSize() + "\n");      
        
        for (String word : s.getWords()) {
            Words.append(word + "\n");
        }
        }
        else if ("Word Search".equals(game)) {
            char[][] letters = new char[6][6];
        
        letters[0][0] = Let00.getText().charAt(0);
        letters[0][1] = Let01.getText().charAt(0);
        letters[0][2] = Let02.getText().charAt(0);
        letters[0][3] = Let03.getText().charAt(0);
        letters[0][4] = Let04.getText().charAt(0);
        letters[0][5] = Let05.getText().charAt(0);
        letters[1][0] = Let10.getText().charAt(0);
        letters[1][1] = Let11.getText().charAt(0);
        letters[1][2] = Let12.getText().charAt(0);
        letters[1][3] = Let13.getText().charAt(0);
        letters[1][4] = Let14.getText().charAt(0);
        letters[1][5] = Let15.getText().charAt(0);
        letters[2][0] = Let20.getText().charAt(0);
        letters[2][1] = Let21.getText().charAt(0);
        letters[2][2] = Let22.getText().charAt(0);
        letters[2][3] = Let23.getText().charAt(0);
        letters[2][4] = Let24.getText().charAt(0);
        letters[2][5] = Let25.getText().charAt(0);
        letters[3][0] = Let30.getText().charAt(0);
        letters[3][1] = Let31.getText().charAt(0);
        letters[3][2] = Let32.getText().charAt(0);
        letters[3][3] = Let33.getText().charAt(0);
        letters[3][4] = Let34.getText().charAt(0);
        letters[3][5] = Let35.getText().charAt(0);
        letters[4][0] = Let40.getText().charAt(0);
        letters[4][1] = Let41.getText().charAt(0);
        letters[4][2] = Let42.getText().charAt(0);
        letters[4][3] = Let43.getText().charAt(0);
        letters[4][4] = Let44.getText().charAt(0);
        letters[4][5] = Let45.getText().charAt(0);
        letters[5][0] = Let50.getText().charAt(0);
        letters[5][1] = Let51.getText().charAt(0);
        letters[5][2] = Let52.getText().charAt(0);
        letters[5][3] = Let53.getText().charAt(0);
        letters[5][4] = Let54.getText().charAt(0);
        letters[5][5] = Let55.getText().charAt(0);
        
        WordSearchBoard board = new WordSearchBoard(letters);
        Lexicon lex = null;
        try {
            lex = new Lexicon("words.txt");
        } 
        catch (FileNotFoundException ex) {
            Logger.getLogger(Boggle.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (IOException ex) {
            Logger.getLogger(Boggle.class.getName()).log(Level.SEVERE, null, ex);
        } 
        WordSearcher s = new WordSearcher(6, lex, board);
        s.search();
        
        Words.setText("Number of words = " + s.getSize() + "\n");      
        
        for (String word : s.getWords()) {
            Words.append(word + "\n");
        }
        }
    }//GEN-LAST:event_SolveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Solver().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoggleBoard;
    private javax.swing.JTextField Char00;
    private javax.swing.JTextField Char01;
    private javax.swing.JTextField Char02;
    private javax.swing.JTextField Char03;
    private javax.swing.JTextField Char10;
    private javax.swing.JTextField Char11;
    private javax.swing.JTextField Char12;
    private javax.swing.JTextField Char13;
    private javax.swing.JTextField Char20;
    private javax.swing.JTextField Char21;
    private javax.swing.JTextField Char22;
    private javax.swing.JTextField Char23;
    private javax.swing.JTextField Char30;
    private javax.swing.JTextField Char31;
    private javax.swing.JTextField Char32;
    private javax.swing.JTextField Char33;
    private javax.swing.JComboBox Games;
    private javax.swing.JTextField Let00;
    private javax.swing.JTextField Let01;
    private javax.swing.JTextField Let02;
    private javax.swing.JTextField Let03;
    private javax.swing.JTextField Let04;
    private javax.swing.JTextField Let05;
    private javax.swing.JTextField Let10;
    private javax.swing.JTextField Let11;
    private javax.swing.JTextField Let12;
    private javax.swing.JTextField Let13;
    private javax.swing.JTextField Let14;
    private javax.swing.JTextField Let15;
    private javax.swing.JTextField Let20;
    private javax.swing.JTextField Let21;
    private javax.swing.JTextField Let22;
    private javax.swing.JTextField Let23;
    private javax.swing.JTextField Let24;
    private javax.swing.JTextField Let25;
    private javax.swing.JTextField Let30;
    private javax.swing.JTextField Let31;
    private javax.swing.JTextField Let32;
    private javax.swing.JTextField Let33;
    private javax.swing.JTextField Let34;
    private javax.swing.JTextField Let35;
    private javax.swing.JTextField Let40;
    private javax.swing.JTextField Let41;
    private javax.swing.JTextField Let42;
    private javax.swing.JTextField Let43;
    private javax.swing.JTextField Let44;
    private javax.swing.JTextField Let45;
    private javax.swing.JTextField Let50;
    private javax.swing.JTextField Let51;
    private javax.swing.JTextField Let52;
    private javax.swing.JTextField Let53;
    private javax.swing.JTextField Let54;
    private javax.swing.JTextField Let55;
    private javax.swing.JLayeredPane Pane;
    private javax.swing.JButton Solve;
    private javax.swing.JScrollPane Word;
    private javax.swing.JPanel WordSearchBoard;
    private javax.swing.JTextArea Words;
    // End of variables declaration//GEN-END:variables
}
